name: 'Install ZTools'
description: 'Install ZTools modules and optionally run a configuration script.'
inputs:
  config-script:
    description: 'Optional path to a PowerShell configuration script.'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Install ZTools
      shell: pwsh
      run: |
        & "${{ github.action_path }}/src/Install-ZTools.ps1" -ConfigScript "${{ inputs.config-script }}"
