name: Auto Document README

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  auto-doc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate documentation
        uses: tj-actions/auto-doc@v3.6.0

      - name: Verify changed files
        id: verify
        uses: tj-actions/verify-changed-files@v8.6
        with:
          files: |
            README.md

      - name: Commit changes
        if: steps.verify.outputs.files_changed == 'true'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: ${{ github.head_ref }}
          commit_message: "chore: update README with auto-doc"
          file_pattern: README.md
